### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by scto** [itsvks19/LayoutEditor#10]
### What happened?

App crashed as i deleted old projects

### What's the expected behavior?

No crash :-)

### Relevant log output

```shell
Manufacturer: Google
Device: Pixel3XL
SDK: 31
Release: 12
Incremental: 8029091
App version: 0.4.0-alpha

java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.itsvks.layouteditor.adapters.ProjectListAdapter.lambda$deleteProject$5$com-itsvks-layouteditor-adapters-ProjectListAdapter(ProjectListAdapter.java:210)
	at com.itsvks.layouteditor.adapters.ProjectListAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)


Sat Dec 03 15:57:11 GMT+01:00 2022
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by itsvks19** [comment]
You can use the latest release, this issue has been fixed.

**Comment by itsvks19** [comment]
If it is not fixed then you can tell me.
