### ISSUE TITLE
[Bug]: App crashes when adding drawables

### ISSUE THREAD

**Issue by PranavPurwar** [itsvks19/LayoutEditor#15]
### What happened?

the app crashed when I tried to add a PNG file to Drawable Manager.

### What's the expected behavior?

No crash and successful import

### Relevant log output

```shell
SDK: 28
App version: 0.5.0-alpha

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:2036)
	at com.itsvks.layouteditor.activities.DrawableManagerActivity.addDrawable(DrawableManagerActivity.java:141)
	at com.itsvks.layouteditor.activities.DrawableManagerActivity.-$$Nest$maddDrawable(Unknown Source:0)
	at com.itsvks.layouteditor.activities.DrawableManagerActivity$1.onPickFile(DrawableManagerActivity.java:95)
	at com.itsvks.layouteditor.utils.FilePicker.lambda$new$0$com-itsvks-layouteditor-utils-FilePicker(FilePicker.java:24)
	at com.itsvks.layouteditor.utils.FilePicker$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:149)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
	at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:109)
	at android.app.Fragment.performStart(Fragment.java:2548)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1334)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3051)
	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3008)
	at android.app.FragmentController.dispatchStart(FragmentController.java:193)
	at android.app.Activity.performStart(Activity.java:7264)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2970)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepkrg17** [comment]
What was the image file path?

**Comment by PranavPurwar** [comment]
It only crashes when i select files from Downloads section of File Picker. It should be something like downloads://smth.png
![Screenshot_2022-12-10-10-02-09-512_com android documentsui](https://user-images.githubusercontent.com/75154889/206829242-ccc453f1-6e96-4fc5-92ea-3c9ab585b81a.jpg)

**Comment by itsvks19** [comment]
I know its reason, I will fix it when I get time. My exam is about to come so I am preparing for my exam.

Till then you(@PranavPurwar) can select image from other path.
