### ISSUE TITLE
[Bug]:  crash 

### ISSUE THREAD

**Issue by sb-codz** [itsvks19/LayoutEditor#22]
### What happened?

drag drops 

### What's the expected behavior?

all time crash

### Relevant log output

```shell
Manufacturer: Xiaomi
Device: Redmi6Pro
SDK: 28
Release: 9
Incremental: V12.0.4.0.PDMMIXM
App version: 0.5.0-alpha

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setLayoutParams(android.view.ViewGroup$LayoutParams)' on a null object reference
	at com.itsvks.layouteditor.editor.layouts.EditorLayout$1.onDrag(EditorLayout.java:139)
	at android.view.View.callDragEventHandler(View.java:24285)
	at android.view.View.dispatchDragEvent(View.java:24276)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1776)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1758)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:6504)
	at android.view.ViewRootImpl.access$1000(ViewRootImpl.java:139)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4371)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)


Thu Feb 09 08:31:44 GMT+05:30 2023
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by itsvks19** [comment]
How to reproduce?
