### ISSUE TITLE
Bug: Crash

### ISSUE THREAD

**Issue by andihasan97** [itsvks19/LayoutEditor#3]
When I try to open a project that was created before the app update crashed, I'm using the latest  app v0.4.0-alpha

Report:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsvks.layouteditor/com.itsvks.layouteditor.activities.EditorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.addView(android.view.View)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3740)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8192)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.addView(android.view.View)' on a null object reference
	at com.itsvks.layouteditor.tools.XmlLayoutParser.parseFromXml(XmlLayoutParser.java:109)
	at com.itsvks.layouteditor.editor.layouts.EditorLayout.loadLayoutFromParser(EditorLayout.java:257)
	at com.itsvks.layouteditor.activities.EditorActivity.onCreate(EditorActivity.java:148)
	at android.app.Activity.performCreate(Activity.java:8119)
	at android.app.Activity.performCreate(Activity.java:8103)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1359)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3713)
	... 11 more


SDK: 30
Release: 11
Incremental: eng.compil.20220822.174220


Fri Nov 18 07:46:47 GMT+07:00 2022
```

**Comment by itsvks19** [comment]
Try [this](https://github.com/itsvks19/LayoutEditor/releases/tag/v0.4.0-alpha) version.

**Comment by andihasan97** [comment]
> Try [this](https://github.com/itsvks19/LayoutEditor/releases/tag/v0.4.0-alpha) version.
Still the same crash can't open

**Comment by itsvks19** [comment]
Have you cleared the data of the app??

**Comment by andihasan97** [comment]
I didn't delete the application data, it will make all the projects disappear, and I deleted the application data earlier my project was lost and I have to start all over again😂, no problem

**Comment by itsvks19** [comment]
I will add a backup system soon.
