### ISSUE TITLE
[Bug]: Error Vector Image

### ISSUE THREAD

**Issue by moderGamer** [itsvks19/LayoutEditor#37]
### What happened?

Manufacturer: samsung
Device: SM-A107F
SDK: 30
Android: 11
Model: A107FXXS8CVL1
App version: 0.6.0-alpha

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.itsvks.layouteditor.ProjectFile.getColorsPath()' on a null object reference
	at com.itsvks.layouteditor.fragments.resources.ColorFragment.onViewCreated(ColorFragment.java:58)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:248)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8231)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3872)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Sun Mar 12 12:42:43 GMT+03:30 2023

### What's the expected behavior?

error not Show Vector Image

### Relevant log output

```shell
can You Send ie Telgram for me?
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by moderGamer** [comment]
@itsvks19 import Layout not Work Plz Fixeing in bug

**Comment by itsvks19** [comment]
Try latest build for the previous issue.

**Comment by itsvks19** [comment]
> @itsvks19 import Layout not Work Plz Fixeing in bug

Only works for widgets that is avaliable in LayoutEditor.

**Comment by moderGamer** [comment]
> 

Just a few minutes ago, I installed the latest action. Send me your Telegram ID

**Comment by itsvks19** [comment]
CoordinatorLayout and ConstraintLayout is not avaliable.

**Comment by itsvks19** [comment]
> > 
> 
> Just a few minutes ago, I installed the latest action. Send me your Telegram ID

Check my profile on GitHub

**Comment by moderGamer** [comment]
> > > 
> > 
> > 
> > Just a few minutes ago, I installed the latest action. Send me your Telegram ID
> 
> Check my profile on GitHub

ok

**Comment by moderGamer** [comment]
I was reported, you can send a message to this ID in Telegram, @Injectormain

**Comment by itsvks19** [comment]
You can join discord.

**Comment by moderGamer** [comment]
> You can join discord.

Discord is banned for Iran and I don't have enough space on my mobile either

**Comment by itsvks19** [comment]
@moderGamer Okay. Nevermind.
