### ISSUE TITLE
[BUG]:  App crash

### ISSUE THREAD

**Issue by andihasan97** [itsvks19/LayoutEditor#5]
**Describe the bug**
I can't open the project I created just yesterday, the app crashes

**Expected behavior**
No crashes 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [VivoY15]
 - OS: [android 11]
 - Version [1901]

**Additional context**
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsvks.layouteditor/com.itsvks.layouteditor.activities.EditorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3740)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8192)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at com.itsvks.layouteditor.tools.XmlLayoutParser.applyAttributes(XmlLayoutParser.java:151)
	at com.itsvks.layouteditor.tools.XmlLayoutParser.parseFromXml(XmlLayoutParser.java:137)
	at com.itsvks.layouteditor.editor.layouts.EditorLayout.loadLayoutFromParser(EditorLayout.java:257)
	at com.itsvks.layouteditor.activities.EditorActivity.onCreate(EditorActivity.java:148)
	at android.app.Activity.performCreate(Activity.java:8119)
	at android.app.Activity.performCreate(Activity.java:8103)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1359)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3713)
	... 11 more

SDK: 30
Release: 11
Incremental: eng.compil.20220822.174220

Sun Nov 20 05:36:08 GMT+07:00 2022

**Comment by itsvks19** [comment]
How can I reproduce this?

**Comment by itsvks19** [comment]
@andihasan97 Try latest build.

**Comment by andihasan97** [comment]
> @andihasan97 Try [latest build.](https://github.com/itsvks19/LayoutEditor/actions/runs/3507007006)

@itsvks19Still Crash

Manufacturer: vivoDevice: vivo1901SDK: 30
Release: 11
Incremental: eng.compil.20220822.174220
App version: 0.4.0-alpha

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itsvks.layouteditor/com.itsvks.layouteditor.activities.EditorActivity}: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3740)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8192)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
	at android.view.ViewGroup.addView(ViewGroup.java:5054)
	at com.itsvks.layouteditor.editor.layouts.EditorLayout.addView(EditorLayout.java:845)
	at android.view.ViewGroup.addView(ViewGroup.java:5036)
	at com.itsvks.layouteditor.editor.layouts.EditorLayout.loadLayoutFromParser(EditorLayout.java:259)
	at com.itsvks.layouteditor.activities.EditorActivity.onCreate(EditorActivity.java:148)
	at android.app.Activity.performCreate(Activity.java:8119)
	at android.app.Activity.performCreate(Activity.java:8103)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1359)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3713)
	... 11 more


Sun Nov 20 15:03:38 GMT+07:00 2022

**Comment by itsvks19** [comment]
@andihasan97 How did this happen? Or how can I reproduce it?

**Comment by itsvks19** [comment]
I can't reproduce it so I close this issue.
