### ISSUE TITLE
EditText Crashed

### ISSUE THREAD

**Issue by RMDragneel** [itsvks19/LayoutEditor#52]
when the widget dragged or passes over the edittext it focuses and when dropped there the app crashes

**Comment by itsvks19** [comment]
Crash log?

**Comment by RMDragneel** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.ClipData.getItemCount()' on a null object reference
	at android.widget.Editor.onDrop(Editor.java:2882)
	at android.widget.TextView.onDragEvent(TextView.java:13047)
	at android.view.View.callDragEventHandler(View.java:27120)
	at android.view.View.dispatchDragEvent(View.java:27108)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1831)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1831)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1831)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1831)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1831)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1831)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1831)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1831)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:8045)
	at android.view.ViewRootImpl.access$1400(ViewRootImpl.java:240)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5738)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:264)
	at android.app.ActivityThread.main(ActivityThread.java:8312)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)


Tue Jan 23 19:46:35 GMT+08:00 2024
